module.exports = {
    UserService: require('./UserService'),
    PriceService: require('./PriceService'),
    MasterService: require('./MasterService'),
    ReturnService: require('./ReturnService'),
    OpnameService: require('./OpnameService'),
    ProductService: require('./ProductService'),
    GetDescService: require('./GetDescService'),
    ScanoutService: require('./ScanoutService'),
    // ReceiveService: require('./ReceiveService'),
    PuttingService: require('./PuttingService'),
    PartnerService: require('./PartnerService'),
    PackageService: require('./PackageService'),
    ShipmentService: require('./ShipmentService'),
    LocationService: require('./LocationService'),
    TransferService: require('./TransferService'),
    InventoryService: require('./InventoryService'),
    SalesOrderService: require('./SalesOrderService'),
    PurchaseOrderService: require('./PurchaseOrderService'),
    SalesQuotationService: require('./SalesQuotationService'),
    InventoryRequestService: require('./InventoryRequestService'),
    InventoryReceiptService: require('./InventoryReceiptService'),
}