module.exports = {
    UserService: require('./UserService'),
    MasterService: require('./MasterService'),
    OpnameService: require('./OpnameService'),
    ProductService: require('./ProductService'),
    GetDescService: require('./GetDescService'),
    ScanoutService: require('./ScanoutService'),
    PuttingService: require('./PuttingService'),
    ShipmentService: require('./ShipmentService'),
    LocationService: require('./LocationService'),
    TransferService: require('./TransferService'),
    InventoryService: require('./InventoryService'),
    SalesOrderService: require('./SalesOrderService'),
    InventoryReceiptService: require('./InventoryReceiptService'),
}